---

- name: Testing
  hosts: localhost
  # https://blog.codecentric.de/en/2017/06/debug-ansible-playbooks-like-pro/
  strategy: debug
  connection: local
  gather_facts: yes

  vars:
    lxc_containers_python_path: "/usr/bin/python"

  tasks:

    - name: Confirm python is installed in container
      delegate_to: "{{ item }}"
      delegate_facts: false
      raw: "test -e {{ lxc_containers_python_path }}"
      register: python_install_check
      failed_when: python_install_check['rc'] not in [0, 1]
      changed_when: false
      with_items:
        - "{{ groups['all'] }}"

    # item.0 is the key of the item
    # item.1 is the value of the item
    # - name: DEBUG | Display variable
    #   debug:
    #     msg: "key is {{ item.0 }}, value is {{ item.1 }}"
    #   with_indexed_items:
    #     - "{{ python_install_check['results'] }}"

    # - name: DEBUG | Python install check results with index
    #   debug:
    #     msg: >-
    #       {{ item.1.item }} |
    #       {{ 'Python is installed' if ( item.1.rc == 0)
    #           else 'Python is NOT installed'
    #       }}
    #   #when: item.1.rc == 1
    #   with_indexed_items:
    #     - "{{ python_install_check['results'] }}"


    # - name: DEBUG | Python install check results with items
    #   debug:
    #     msg: >-
    #       {{ item.item }} |
    #       {{ 'Python is installed' if ( item.rc == 0)
    #           else 'Python is NOT installed'
    #       }}
    #   #when: item.1.rc == 1
    #   with_items:
    #     - "{{ python_install_check['results'] }}"


    # - name: DEBUG | Python install check results using with_items
    #   debug:
    #     var: item
    #   with_items:
    #     - "{{ python_install_check['results'] }}"
    #   loop_control:
    #     label: "{{ item.item }}"

    - name: DEBUG | Python install check results using loop
      debug:
        var: item
      loop:
        "{{ python_install_check['results'] | flatten(levels=1) }}"
      loop_control:
        label: "{{ item.item }}"

      #loop:
      #  - "{{ python_install_check['results'] | flatten(levels=1)}}"
      #loop_control:
      #  label: "{{ item.item }}"

    - name: DEBUG | Python install check results
      debug:
        var: python_install_check['results']
        verbosity: 1

    - name: DEBUG | Variables for host
      debug:
        var: hostvars[item]
        verbosity: 1
      with_items:
        - "{{ groups['all'] }}"
...
