---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv


# This file is for variables that apply to all hosts in this inventory.

# Hyper-V NAT-connected Squid instance for package caching
# lxd_containers_proxy_server: "http://172.23.194.68:3128/"

...
