---

# vim: ts=2:sw=2:et:ft=yaml
# -*- mode: yaml; indent-tabs-mode: nil; tab-width: 2 -*-
# code: language=yaml insertSpaces=true tabSize=2

# https://github.com/atc0005/ansible-playbook-lxd-testenv
# https://github.com/atc0005/ansible-role-lxd-testenv


# These are LXD containers, so use lxd connection type when making initial
# connections for setup purposes.
ansible_connection: "lxd"

# lxd does not support remote_user (i.e., this setting) and defaults to 'root'
ansible_user: "root"

# Explictly set here instead of within playbooks that manipulate containers
# created from this testing inventory. This allows those same playbooks
# (at least in theory) to be used for truly remote hosts as well.
connection: local

...
